version: '3'

services:
  longrunningapp:
    image: longrunningapp
    build:
      context: .\longrunningapp
      dockerfile: Dockerfile
    depends_on:
      - redis

  redis:
    image: redis
    ports:
      - "6379:6379"

networks:
  default:
    external:
      name: local_development_network