version: '3'

services:
  longrunningapp:
    image: cgot/longrunningapp
    build:
      context: ./longrunningapp
      dockerfile: Dockerfile
    depends_on:
      - redis

  redis:
    image: redis
    ports:
      - "6379:6379"